### ISSUE TITLE
bypass namespace RBAC in IPPool with a simple annotation

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#3260] opened 2023-09-26 07:48 UTC
# Expected Behavior

when a namespace has one IPPool assigned it cannot deploy pods using other's IPPool, pod/deployment/other kind of resources should fail.

# Actual Behavior

with ovn.kubernetes.io/ip_address or ovn.kubernetes.io/ip_pool annotation you can specify IPs belonging to others' IPPool.
Even the provided webhook is unable to check this violation.

# Steps to Reproduce the Problem

1. create two pools, one per namespace
```
apiVersion: kubeovn.io/v1
kind: IPPool
metadata:
  name: pool-ns1
spec:
  subnet:  subnet1-vpc
  ips:
  - "10.0.10.16/29"
  namespaces:
  - ns1

---
apiVersion: kubeovn.io/v1
kind: IPPool
metadata:
  name: pool-ns2
spec:
  subnet:  subnet1-vpc
  ips:
  - "10.0.10.24/29"
  namespaces:
  - ns2
```

2. create a pod, in namespace ns1, but using a ip pool belonging to ns2 namespace

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox-21
  labels:
    app: busybox
  annotations:
    ovn.kubernetes.io/logical_switch: subnet1-vpc
    ovn.kubernetes.io/ip_address: 10.0.10.26
  namespace: ns1
spec:
  containers:
  - name: busybox
```

3. pod will get the requested ip allocated and starts normally

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
1.28.2
  ```

- kube-ovn version:
  
  ```
1.12.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

**Comment by patriziobassi** [comment] 2023-09-26 10:47
dear @zhangzujian shouldn't this be marked as a bug instead of a feature?

**Comment by zhangzujian** [comment] 2023-09-27 01:40
This behavior is by design. Pod's annotation has a higher priority than the namespace.

**Comment by patriziobassi** [comment] 2023-09-27 02:51
@zhangzujian I understand. But in a multitenant environment you cannot trust the developer: if you configured a IPPool for namespace, shorter than the overall subnet cidr, why should you allow a user to bypass that restriction? In that case you should add that specific address to the pool (or create a new One). My 2 cents.

**Comment by zhangzujian** [comment] 2023-09-27 03:26
Label `feature` means this is a feature request, or the problem can be resolved by adding a new feature.

**Comment by patriziobassi** [comment] 2023-09-27 03:42
@zhangzujian sure, thx for explaination. what about a contribute (patch) on the webhook in order to check this ippool boundary? So it's not part of the core ipam code, easier to test and it's optionally activated by users.

**Comment by patriziobassi** [comment] 2024-03-15 16:29
Hi, i wonder if there is any way to fix this at the moment, can you please reopen it?

**Closed** 2024-05-26 00:00 UTC
Labels: feature, no-issue-activity
