### ISSUE TITLE
[BUG] ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#4741] opened 2024-11-18 08:05 UTC
### Kube-OVN Version

v1.11.20

### Kubernetes Version

v1.29.10

control-plane   20m   v1.29.10   192.168.180.129   <none>        Ubuntu 24.04.1 LTS   6.8.0-48-generic   containerd://1.7.22

### Operation-system/Kernel Version

Ubuntu 24.04.1 LTS   6.8.0-48-generic 

### Description

```bash

(ae86) ➜  kubespray-2.25.1 kubectl get deploy -A -o wide | grep kube-ovn
kube-system   kube-ovn-controller   1/1     1            1           16m   kube-ovn-controller   docker.io/kubeovn/kube-ovn:v1.11.20                          app=kube-ovn-controller
kube-system   kube-ovn-monitor      1/1     1            1           16m   kube-ovn-monitor      docker.io/kubeovn/kube-ovn:v1.11.20                          app=kube-ovn-monitor
kube-system   ovn-central           0/1     1            0           16m   ovn-central           docker.io/kubeovn/kube-ovn:v1.11.20                          app=ovn-central
(ae86) ➜  kubespray-2.25.1
(ae86) ➜  kubespray-2.25.1
(ae86) ➜  kubespray-2.25.1
(ae86) ➜  kubespray-2.25.1 kgp
NAMESPACE     NAME                                   READY   STATUS              RESTARTS        AGE    IP                NODE   NOMINATED NODE   READINESS GATES
kube-system   coredns-69db55dd76-snv67               0/1     ContainerCreating   0               15m    <none>            ae86   <none>           <none>
kube-system   dns-autoscaler-6d5984c657-7jpb8        0/1     ContainerCreating   0               15m    <none>            ae86   <none>           <none>
kube-system   kube-apiserver-ae86                    1/1     Running             0               17m    192.168.180.129   ae86   <none>           <none>
kube-system   kube-controller-manager-ae86           1/1     Running             4 (2m58s ago)   17m    192.168.180.129   ae86   <none>           <none>
kube-system   kube-multus-ds-arm64-ptmbx             1/1     Running             0               16m    192.168.180.129   ae86   <none>           <none>
kube-system   kube-ovn-cni-ck6xc                     0/1     CrashLoopBackOff    4 (9s ago)      108s   192.168.180.129   ae86   <none>           <none>
kube-system   kube-ovn-controller-7cf488b7f9-nq8hc   1/1     Running             1 (45s ago)     108s   192.168.180.129   ae86   <none>           <none>
kube-system   kube-ovn-monitor-786cccbc58-8879v      1/1     Running             0               108s   192.168.180.129   ae86   <none>           <none>
kube-system   kube-ovn-pinger-94959                  0/1     Terminating         0               15m    <none>            ae86   <none>           <none>
kube-system   kube-proxy-sb9cg                       1/1     Running             0               108s   192.168.180.129   ae86   <none>           <none>
kube-system   kube-scheduler-ae86                    1/1     Running             4 (2m58s ago)   17m    192.168.180.129   ae86   <none>           <none>
kube-system   nodelocaldns-jmkwb                     1/1     Running             0               15m    192.168.180.129   ae86   <none>           <none>
kube-system   ovn-central-f8c5b488-lzgr5             0/1     CrashLoopBackOff    4 (21s ago)     108s   192.168.180.129   ae86   <none>           <none>
kube-system   ovs-ovn-84fvz                          1/1     Running             0               16m    192.168.180.129   ae86   <none>           <none>
(ae86) ➜  kubespray-2.25.1 kubectl logs -f -n kube-system   kube-ovn-cni-ck6xc
Defaulted container "cni-server" out of: cni-server, install-cni (init)
ovsdb-server is running with pid 32420
ovs-vswitchd is running with pid 32650
iptables v1.8.7 (nf_tables)
I1118 08:00:48.615856   97616 cniserver.go:35]
-------------------------------------------------------------------------------
Kube-OVN:
  Version:       v1.11.20
  Build:         2024-10-15_09:45:18
  Commit:        git-4e7fb34
  Go Version:    go1.22.8
  Arch:          arm64
-------------------------------------------------------------------------------
E1118 08:00:48.616855   97616 init.go:19] failed to set checksum off for genev_sys_6081, exit status 92
I1118 08:00:48.619282   97616 config.go:167] node name not specified in command line parameters, fall back to the environment variable
I1118 08:00:48.619298   97616 config.go:336] no --kubeconfig, use in-cluster kubernetes config
I1118 08:00:48.619523   97616 k8s.go:25] succeeded to dial apiserver "10.233.0.1:443"
I1118 08:00:48.625211   97616 config.go:187] daemon config: &{ ens160 br-phy 1400 1360 false mirror0 /run/openvswitch/kube-ovn-daemon.sock /run/openvswitch/db.sock  0x400031aea0 0x40005262f0 ae86 10.233.0.0/16  ovn-cluster join true false false 10665 geneve /etc/cni/net.d /kube-ovn/01-kube-ovn.conflist 01-kube-ovn.conflist provider  - --cni-conf-name=1-kube-ovn.conflist kube-system external true true false 8100 8101 /var/lib/kubelet}
I1118 08:00:48.628617   97616 cniserver.go:196] finish adding chassis annotation
I1118 08:00:48.636908   97616 ovs_linux.go:690] wait ovn0 gw ready
I1118 08:00:48.737831   97616 ovs.go:40] 100.64.0.2 network ready after 1 ping, gw 100.64.0.1
I1118 08:00:48.742918   97616 server.go:33] start listen on /run/openvswitch/kube-ovn-daemon.sock
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:48Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:48Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:49Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:49Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:49Z" level=error msg="Bad return code from 'ipset list'." error="exit status 1" family=inet stderr="ipset v7.15: Kernel and userspace incompatible: settype hash:ip,port with revision 7 not supported by userspace.\n"
time="2024-11-18T08:00:49Z" level=warning msg="Failed to resync with dataplane" error="exit status 1" family=inet
time="2024-11-18T08:00:49Z" level=error msg="Failed to read IP sets" error="exit status 1" family=inet
time="2024-11-18T08:00:49Z" level=panic msg="Failed to update IP sets after multiple retries." family=inet
E1118 08:00:49.889214   97616 runtime.go:79] Observed a panic: &logrus.Entry{Logger:(*logrus.Logger)(0xba57d5723480), Data:logrus.Fields{"family":"inet"}, Time:time.Date(2024, time.November, 18, 8, 0, 49, 889062013, time.Local), Level:0x0, Caller:(*runtime.Frame)(nil), Message:"Failed to update IP sets after multiple retries.", Buffer:(*bytes.Buffer)(nil), Context:context.Context(nil), err:""} (&{0xba57d5723480 map[family:inet] 2024-11-18 08:00:49.889062013 +0000 UTC m=+1.285410191 panic <nil> Failed to update IP sets after multiple retries. <nil> <nil> })
goroutine 101 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0xba57d43c7cc0, 0x400023d420})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.16/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40007b81c0?})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.16/pkg/util/runtime/runtime.go:49 +0x78
panic({0xba57d43c7cc0?, 0x400023d420?})
	/opt/hostedtoolcache/go/1.22.8/x64/src/runtime/panic.go:770 +0x124
github.com/sirupsen/logrus.(*Entry).log(0x4000290fc0, 0x0, {0x40008a4870, 0x30})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x494
github.com/sirupsen/logrus.(*Entry).Log(0x4000290fc0, 0x0, {0x4000b598d8?, 0x5?, 0xe6c288875618?})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/alauda/felix/ipsets.(*IPSets).ApplyUpdates(0x40004f9680)
	/home/runner/go/pkg/mod/github.com/kubeovn/felix@v0.0.0-20220325073257-c8a0f705d139/ipsets/ipsets.go:293 +0x578
github.com/kubeovn/kube-ovn/pkg/daemon.(*Controller).setIPSet(0x4000306000)
	/home/runner/work/kube-ovn/kube-ovn/pkg/daemon/gateway_linux.go:121 +0x3a8
github.com/kubeovn/kube-ovn/pkg/daemon.(*Controller).Run(0x4000306000, 0x4000422780)
	/home/runner/work/kube-ovn/kube-ovn/pkg/daemon/controller.go:643 +0x300
created by github.com/kubeovn/kube-ovn/cmd/daemon.CmdMain in goroutine 1
	/home/runner/work/kube-ovn/kube-ovn/cmd/daemon/cniserver.go:83 +0x4c4
panic: (*logrus.Entry) 0x400023d420 [recovered]
	panic: (*logrus.Entry) 0x400023d420

goroutine 101 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40007b81c0?})
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.16/pkg/util/runtime/runtime.go:56 +0xe0
panic({0xba57d43c7cc0?, 0x400023d420?})
	/opt/hostedtoolcache/go/1.22.8/x64/src/runtime/panic.go:770 +0x124
github.com/sirupsen/logrus.(*Entry).log(0x4000290fc0, 0x0, {0x40008a4870, 0x30})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x494
github.com/sirupsen/logrus.(*Entry).Log(0x4000290fc0, 0x0, {0x4000b598d8?, 0x5?, 0xe6c288875618?})
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Panic(...)
	/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
github.com/alauda/felix/ipsets.(*IPSets).ApplyUpdates(0x40004f9680)
	/home/runner/go/pkg/mod/github.com/kubeovn/felix@v0.0.0-20220325073257-c8a0f705d139/ipsets/ipsets.go:293 +0x578
github.com/kubeovn/kube-ovn/pkg/daemon.(*Controller).setIPSet(0x4000306000)
	/home/runner/work/kube-ovn/kube-ovn/pkg/daemon/gateway_linux.go:121 +0x3a8
github.com/kubeovn/kube-ovn/pkg/daemon.(*Controller).Run(0x4000306000, 0x4000422780)
	/home/runner/work/kube-ovn/kube-ovn/pkg/daemon/controller.go:643 +0x300
created by github.com/kubeovn/kube-ovn/cmd/daemon.CmdMain in goroutine 1
	/home/runner/work/kube-ovn/kube-ovn/cmd/daemon/cniserver.go:83 +0x4c4

```

### Steps To Reproduce

1. all in one deploy with kubespray

### Current Behavior

fail

### Expected Behavior

ok

**Comment by bobz965** [comment] 2024-11-18 08:29
1.12.20 does not have this issue

**Comment by zhangzujian** [comment] 2024-11-18 10:06
duplicate of #4540.

**Closed** 2024-11-19 05:49 UTC
Labels: bug
